version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: HabitTrack
    environment:
      POSTGRES_DB: HabitTrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always